#!/usr/bin/env python3
"""Item B — the perennial-question generator on the REAL 6-axis coordinate structure.

Reads reading-SB's DATA_occupied_tuples_for_designSB (512 coded figures, 365 distinct
occupied 6-tuples of 275,184 possible = 0.13% occupancy). Builds an interactive page:
 - the headline occupancy stat (365 / 275,184; the empty 99.87% = the perennial space);
 - the per-axis marginal distribution (the spin weights) with the §2.8 bias-visibility flag
   (the corpus skew — personal-agentive 232/512 — is SHOWN, not hidden);
 - the generator: spin a coordinate weighted by the real marginals →
     OCCUPIED = a real thinker sits here (list them);
     GAP = a coherent framing the corpus has never posed (generated by mutating ONE axis off a
     real occupied coordinate, per reading-SB's caveats: spin near occupied first; not every
     empty cell is coherent — so every gap is one axis from a real thinker).

Usage: build_coordspace.py <occupied_tuples.json> <OUTPUT.html>
"""
import sys, json

AXES = [
  ("epistemic-warrant", "E", "how it knows"),
  ("ontological-commitment", "O", "what it takes to be real"),
  ("inferential-operation", "M", "how it moves"),
  ("telos", "T", "what it is for"),
  ("stance", "S", "its posture"),
  ("ground-world-relation", "G", "world-relation"),
]

def build(data_path, out_path):
    d = json.load(open(data_path))
    marg = d["per_axis_marginals"]
    occ = [{"c": [t["coord"][a] for a, _, _ in AXES], "n": t["n"], "figs": t["figures"]} for t in d["occupied_tuples"]]
    top = max(occ, key=lambda t: t["n"])
    JS = {
      "AXES": [{"k": a, "s": s, "g": g} for a, s, g in AXES],
      "MARG": {a: marg[a] for a, _, _ in AXES},
      "OCC": occ,
      "POSSIBLE": d["possible_full_menu"],
      "NOCC": d["n_distinct_occupied_tuples"],
      "NFIG": d["n_figures"],
      "PCT": d["occupancy_pct_of_full_menu"],
    }
    DATA_JSON = json.dumps(JS, ensure_ascii=False)

    HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>The coordinate space — 365 of 275,184 · Grammar of Meaning</title>
<style>
  :root{--paper:#f7f2e7;--paper2:#fffdf7;--card:#fffefa;--ink:#26221a;--ink2:#5b5346;--ink3:#8a8172;--line:#e4dcc9;--line2:#d0c6ae;--moss:#4b6b46;--moss-d:#33502f;--gold:#b8892f;--gold-bg:#f6ecd4;--myst:#5b53a6;--myst-bg:#eae7f6;--terra:#9c3f37;--mono:ui-monospace,"SF Mono",Menlo,Consolas,monospace;--sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,sans-serif;--serif:"Iowan Old Style","Palatino Linotype",Palatino,Georgia,serif;}
  @media (prefers-color-scheme:dark){:root{--paper:#14130f;--paper2:#1a1813;--card:#1e1b15;--ink:#ece7dc;--ink2:#b3aa98;--ink3:#847c6c;--line:#332f27;--line2:#423d31;--moss:#8fb884;--moss-d:#6c9a62;--gold:#e0b45f;--gold-bg:#2c2410;--myst:#a99ee6;--myst-bg:#221d38;--terra:#d98b80;}}
  *{box-sizing:border-box}
  body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--sans);font-size:15.5px;line-height:1.6;-webkit-font-smoothing:antialiased}
  .wrap{max-width:840px;margin:0 auto;padding:0 22px 90px}
  a{color:var(--moss-d)}@media(prefers-color-scheme:dark){a{color:var(--moss)}}
  header{padding:44px 0 18px;border-bottom:2px solid var(--line2)}
  .eyebrow{font-family:var(--mono);font-size:11.5px;letter-spacing:.16em;text-transform:uppercase;color:var(--gold);margin:0 0 10px}
  .banner{display:inline-block;font-family:var(--mono);font-size:11px;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:#fff;background:var(--myst);padding:4px 10px;border-radius:5px;margin-bottom:14px}
  h1{font-family:var(--serif);font-weight:500;font-size:31px;line-height:1.12;margin:0 0 8px;letter-spacing:-.015em}
  .sub{color:var(--ink2);font-size:16.5px;max-width:64ch;margin:0}
  h2{font-family:var(--serif);font-weight:500;font-size:21px;margin:40px 0 6px}
  p{margin:10px 0}.lead{color:var(--ink2)}
  /* headline stat */
  .stat{display:flex;gap:26px;flex-wrap:wrap;align-items:baseline;margin:22px 0 6px}
  .stat .big{font-family:var(--serif);font-size:46px;font-weight:500;color:var(--myst);line-height:1}
  .stat .of{font-family:var(--serif);font-size:22px;color:var(--ink3)}
  .stat .lab{font-size:13.5px;color:var(--ink2);max-width:34ch}
  .occbar{height:16px;border-radius:99px;background:var(--myst-bg);overflow:hidden;border:1px solid var(--line2);margin:12px 0 2px;position:relative}
  .occbar i{display:block;height:100%;background:var(--moss);min-width:2px}
  .occbar .pct{position:absolute;left:8px;top:50%;transform:translateY(-50%);font-family:var(--mono);font-size:10px;color:var(--ink3)}
  /* generator */
  .gen{background:var(--card);border:1px solid var(--line2);border-radius:16px;padding:20px 22px;margin:18px 0}
  .modes{display:inline-flex;border:1.5px solid var(--line2);border-radius:99px;padding:3px;margin:0 0 16px;flex-wrap:wrap}
  .mode{font-family:var(--sans);font-size:13.5px;padding:7px 15px;border-radius:99px;border:0;background:transparent;color:var(--ink2);cursor:pointer;transition:all .18s}
  .mode.on{background:var(--ink);color:var(--paper);font-weight:600}
  .spin{font-family:var(--sans);font-size:15px;font-weight:600;padding:11px 26px;border-radius:12px;border:0;cursor:pointer;background:var(--myst);color:#fff;margin-left:10px}
  .spin:hover{filter:brightness(1.06)}
  .coord{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:18px 0 4px}
  @media(max-width:620px){.coord{grid-template-columns:repeat(3,1fr)}}
  .cx{background:var(--paper2);border:1px solid var(--line2);border-radius:10px;padding:9px 10px;min-height:78px}
  .cx .ax{font-family:var(--mono);font-size:9px;letter-spacing:.05em;text-transform:uppercase;color:var(--ink3)}
  .cx .val{font-family:var(--serif);font-size:14px;color:var(--ink);margin-top:3px;line-height:1.2;word-break:break-word}
  .cx.diff{border-color:var(--myst);background:var(--myst-bg)}
  .cx.diff .val{color:var(--myst);font-weight:600}
  .verdict{border-radius:12px;padding:14px 16px;margin:6px 0 0;font-size:14.5px}
  .verdict.occ{background:#e8efe2;color:var(--moss-d)}
  @media(prefers-color-scheme:dark){.verdict.occ{background:#1c2a18;color:var(--moss)}}
  .verdict.gap{background:var(--myst-bg);color:var(--myst)}
  .verdict b{font-weight:700}
  .figs{margin:9px 0 0;font-size:13px;color:var(--ink2);line-height:1.7}
  .figs .f{display:inline-block;background:var(--card);border:1px solid var(--line2);border-radius:20px;padding:2px 9px;margin:2px 3px 0 0;font-size:12px}
  .neartag{font-family:var(--mono);font-size:12px;color:var(--ink2);margin-top:8px}
  /* distribution */
  .axblock{margin:14px 0}
  .axhead{display:flex;align-items:baseline;gap:9px;margin:0 0 5px}
  .axhead .k{font-family:var(--serif);font-size:15.5px;color:var(--ink)}
  .axhead .g{font-family:var(--mono);font-size:11px;color:var(--ink3)}
  .bar{display:flex;align-items:center;gap:9px;margin:3px 0}
  .bar .bl{width:150px;font-size:12.5px;color:var(--ink2);text-align:right;flex:none;font-family:var(--mono);font-size:11px}
  .bar .bt{flex:1;height:14px;border-radius:4px;background:var(--line);overflow:hidden}
  .bar .bt i{display:block;height:100%;background:var(--moss)}
  .bar.skew .bt i{background:var(--terra)}
  .bar .bn{font-family:var(--mono);font-size:11px;color:var(--ink3);width:34px;flex:none}
  .flag{background:var(--card);border:1px solid var(--line2);border-left:3px solid var(--terra);border-radius:0 10px 10px 0;padding:12px 16px;margin:14px 0;font-size:14px;color:var(--ink2)}
  .flag b{color:var(--ink)}
  .backlink{display:inline-block;margin:28px 0 0;font-family:var(--mono);font-size:12px}
  .foot{margin-top:40px;padding-top:16px;border-top:1px solid var(--line);font-family:var(--mono);font-size:12px;color:var(--ink3);line-height:1.7}
</style>
</head>
<body>
<div class="wrap">
<header>
  <span class="banner">candidate · Stage 6 = 0 · not a finding</span>
  <p class="eyebrow">the coding lab · the perennial-question generator</p>
  <h1>The coordinate space — 365 of 275,184</h1>
  <p class="sub">Every framing of meaning is a point in a six-axis space — how it knows, what it takes to be real, how it moves, what it is for, its posture, its world-relation. The space has <b>275,184</b> coherent coordinates. The corpus, so far, has posed <b>365</b> of them. The generator spins that space: land on an occupied point and meet the minds who took it; land on an empty one and read a question no one has asked.</p>
</header>

<h2>How much has been thought</h2>
<div class="stat">
  <div><span class="big" id="s-occ">365</span> <span class="of">/ 275,184</span></div>
  <div class="lab">distinct coordinates a real thinker occupies, of all coherent coordinates. <b id="s-pct">0.13%</b> occupancy — the empty <b>99.87%</b> is the perennial-question space.</div>
</div>
<div class="occbar"><i id="occfill"></i><span class="pct">0.13% occupied</span></div>
<p class="lead" style="font-size:13.5px">From <span id="s-fig">512</span> fully-coded figures (insufficient-context figures dropped, mirroring the morphospace). Occupancy shifts slightly after the S151 non-person drop — reading-SB will re-emit; the shape holds.</p>

<h2>Spin the space</h2>
<div class="gen">
  <div class="modes" id="modes">
    <button class="mode on" data-m="any">spin anywhere</button>
    <button class="mode" data-m="occ">meet the minds (occupied)</button>
    <button class="mode" data-m="gap">a question no one asked (gap)</button>
  </div>
  <button class="spin" id="spin">spin →</button>
  <div class="coord" id="coord"></div>
  <div class="verdict" id="verdict" style="display:none"></div>
</div>
<p class="lead" style="font-size:13px">Gaps are generated by moving <b>one axis</b> off a coordinate a real thinker occupies — so every empty point shown sits one step from a real mind, not floating in incoherent space. (Per reading-SB: spin near occupied regions first; not every empty cell is coherent.)</p>

<h2>The spin weights — the real distribution</h2>
<p class="lead">The generator weights each axis by how the 512 figures actually distribute. That distribution is not neutral: the corpus is Abrahamic-heavy, and the weights show it. We surface the skew rather than flatten it — the bias is the data, and hiding it would be the error (§2.8).</p>
<div class="flag"><b>Read the red bars as bias, not truth.</b> <span id="skewnote">personal-agentive fills 232 of 512</span> because the corpus over-represents the traditions that wrote the most and were digitized first — not because that ontology is more correct. The empty coordinates are disproportionately the under-written ones; the generator’s job is to make them visible.</div>
<div id="dist"></div>

<a class="backlink" href="coding-lab.html">← back to the coding lab</a>
<p class="foot">HOW PRODUCED · design-SB, built by build_coordspace.py from reading-SB’s DATA_occupied_tuples_for_designSB_2026-07-15 (512 coded figures; 365 occupied 6-tuples). Item B of the S150 design-SB batch. SCHOLARLY SOURCES · the 6-axis exom coordinate instrument; the S149 bottom-up cluster check; §2.8 bias-visibility. WHAT NEEDS VERIFICATION · (1) not every empty coordinate is internally coherent — gaps are drawn one-axis-from-occupied as a coherence heuristic, not a proof. (2) occupancy re-emits after the S151 non-person drop. (3) candidate demonstrator; Stage 6 = 0; nothing written to the DB.</p>
</div>
<script>
var D = __DATA_JSON__;
(function(){
  var AX=D.AXES, OCC=D.OCC, MARG=D.MARG;
  document.getElementById('s-occ').textContent=D.NOCC;
  document.getElementById('s-pct').textContent=D.PCT.toFixed(2)+'%';
  document.getElementById('s-fig').textContent=D.NFIG;
  document.getElementById('occfill').style.width=Math.max(0.4,D.PCT)+'%';
  // occupied set for O(1) gap-check
  var occSet={}; OCC.forEach(function(t){ occSet[t.c.join('|')]=t; });
  // weighted pickers
  function wpick(counts){ var ks=Object.keys(counts),tot=0; ks.forEach(function(k){tot+=counts[k];});
    var r=Math.floor((tot)* (spinSeed()) ); for(var i=0;i<ks.length;i++){ r-=counts[ks[i]]; if(r<0) return ks[i]; } return ks[ks.length-1]; }
  function wpickOcc(){ var tot=0; OCC.forEach(function(t){tot+=t.n;}); var r=Math.floor(tot*spinSeed());
    for(var i=0;i<OCC.length;i++){ r-=OCC[i].n; if(r<0) return OCC[i]; } return OCC[0]; }
  // deterministic-free randomness (vary by call count so it changes each spin)
  var _c=0; function spinSeed(){ _c++; var x=Math.sin(_c*99991.7+_c*_c*0.113)*43758.5453; return x-Math.floor(x); }
  function genGap(){
    // mutate ONE axis off a weighted-real occupied coordinate → a near-occupied empty point
    for(var tries=0; tries<80; tries++){
      var base=wpickOcc(); var c=base.c.slice();
      var ai=Math.floor(spinSeed()*AX.length); var ax=AX[ai].k;
      var nv=wpick(MARG[ax]); if(nv===c[ai]) continue; c[ai]=nv;
      if(!occSet[c.join('|')]) return {c:c, base:base, ai:ai};
    }
    return null;
  }
  var mode='any';
  document.querySelectorAll('#modes .mode').forEach(function(b){ b.onclick=function(){
    mode=b.getAttribute('data-m'); document.querySelectorAll('#modes .mode').forEach(function(x){x.classList.toggle('on',x===b);}); }; });
  function esc(s){return String(s).replace(/[&<>]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;'}[c];});}
  function renderCoord(c, diffIdx){
    return AX.map(function(a,i){ return '<div class="cx'+(i===diffIdx?' diff':'')+'"><div class="ax">'+a.s+' · '+esc(a.k)+'</div><div class="val">'+esc(c[i])+'</div></div>'; }).join('');
  }
  function spin(){
    var m=mode; if(m==='any') m = spinSeed()<0.5 ? 'occ':'gap';
    var coordEl=document.getElementById('coord'), vEl=document.getElementById('verdict');
    vEl.style.display='block';
    if(m==='occ'){
      var t=wpickOcc();
      coordEl.innerHTML=renderCoord(t.c,-1);
      vEl.className='verdict occ';
      var figs=t.figs.slice(0,16).map(function(f){return '<span class="f">'+esc(f)+'</span>';}).join('');
      vEl.innerHTML='<b>Occupied.</b> '+t.n+' figure'+(t.n>1?'s':'')+' frame meaning at exactly this coordinate — the same six-axis stance, arrived at independently.'
        +'<div class="figs">'+figs+(t.figs.length>16?' <span style="color:var(--ink3)">+'+(t.figs.length-16)+' more</span>':'')+'</div>';
    } else {
      var g=genGap(); if(!g){ vEl.innerHTML='(no coherent gap found near that region — spin again)'; return; }
      coordEl.innerHTML=renderCoord(g.c,g.ai);
      vEl.className='verdict gap';
      var axName=AX[g.ai].k, theirVal=g.base.c[g.ai], someone=g.base.figs[0];
      vEl.innerHTML='<b>A gap — a framing no one has posed.</b> No figure in the corpus holds this exact stance. '
        +'But it sits <b>one axis</b> from a real one: shift <span style="font-family:var(--mono);font-size:12.5px">'+esc(axName)+'</span> back to <span style="font-family:var(--mono);font-size:12.5px">'+esc(theirVal)+'</span> and you land on '+g.base.n+' real thinker'+(g.base.n>1?'s':'')+' (e.g. '+esc(someone)+'). '
        +'<div class="neartag">The perennial question: <i>what would it mean to know '+esc(g.c[0])+', hold '+esc(g.c[1])+', and still reach for '+esc(g.c[3])+' — the way no one yet has?</i></div>';
    }
  }
  document.getElementById('spin').onclick=spin;
  // distribution bars
  var dist=document.getElementById('dist'), skewTop='';
  AX.forEach(function(a){
    var m=MARG[a.k], ks=Object.keys(m).sort(function(x,y){return m[y]-m[x];}), max=m[ks[0]];
    if(a.k==='ontological-commitment') skewTop=ks[0]+' fills '+m[ks[0]]+' of '+D.NFIG;
    var rows=ks.map(function(k,i){ return '<div class="bar'+(i===0?' skew':'')+'"><span class="bl">'+esc(k)+'</span>'
      +'<span class="bt"><i style="width:'+(100*m[k]/max).toFixed(1)+'%"></i></span><span class="bn">'+m[k]+'</span></div>'; }).join('');
    dist.innerHTML+='<div class="axblock"><div class="axhead"><span class="k">'+esc(a.k)+'</span><span class="g">'+a.s+' · '+esc(a.g)+'</span></div>'+rows+'</div>';
  });
  document.getElementById('skewnote').textContent=skewTop;
  spin();
})();
</script>
</body>
</html>"""
    HTML = HTML.replace("__DATA_JSON__", DATA_JSON)
    open(out_path, "w").write(HTML)
    print(f"wrote {out_path} — {len(occ)} occupied tuples, top n={top['n']} ({', '.join(top['c'][:3])}…)")

if __name__ == "__main__":
    build(sys.argv[1], sys.argv[2])
